version: '3.3'
services:
  # equivalent to these interactive commands:
  # docker network create -d bridge postgresql
  # docker run -d --restart=always --network=postgresql --name sdft-db -p 5555:5432 -e POSTGRES_PASSWORD=password sdft-db -c max_wal_size=10GB
  # docker run -d --restart=always --network=postgresql --name sdft-ui -p 8787:8787  -v /home/sdft:/home/rstudio  -e PASSWORD=password sdft-ui
  db:
    image: "sdft/sdft-db:version-1.1.1"
    container_name: sdft-db
    restart: always
    environment:
       POSTGRES_PASSWORD: "your_password"
    command: postgres -c max_wal_size=10GB
    # ports only needed if you want to access the database externally
    # not needed for sdft-ui access
    #ports:
    #  - "5555:5432"
    networks:
      - postgresql

  ui:
    image: "sdft/sdft-ui:version-1.1.1"
    container_name: sdft-ui
    restart: "always"
    environment:
      PASSWORD: "your_password"
    depends_on:
      - db
    volumes:
      - c:/sdft:/home/rstudio
    ports:
      - "8787:8787"
    networks:
       - postgresql

networks:
  postgresql:
       driver: bridge
