setwd("/tmp")
install.packages(c("dplyr", "tidyr", "foreach", "RPostgres", "magrittr", "futile.logger", "stringr", "readr", "DBI", "doParallel", "keyring", "checkmate", "rlang"), repos = "https://cran.rstudio.com/")
unzip("master.zip", exdir="/tmp")
file.rename("sdft-master", "sdft")
system("R CMD build sdft")
install.packages(list.files(path = "/tmp", pattern="sdft_"), repos = NULL)